### ISSUE TITLE
xbee data buffer

### ISSUE THREAD

**Issue by Xujianhong123Allen** [g-ch/xbee_ros_info#1]
请问xbee的数据缓冲区只有256个字节吗，是否可以修改，比如改成1000字节。现在想利用xbee传输ROS的消息类型nav_msgs/Odometry，可以把传输数据String类型改成自己想要的吗

**Comment by g-ch** [comment]
抱歉没预料到有人会评论，才看到，可以改的，用socket串口发送即可，我这里写的只是发送ros info类的消息

**Comment by g-ch** [comment]
建议直接参考socket相关资料，写一个简单的ros节点订阅nav消息，按自己格式发送接收。因为xbee带宽低，直接用mavlink效率很低，只需要单独几个消息的话可以用socket自己写定制处理
